#!/bin/sh
while getopts ":f:h" opt; do
  case $opt in
    f)
   	 	RETURN=$(curl -F c=@- https://ptpb.pw < $OPTARG 2>&1)
			URL=$(echo "$RETURN" | sed -n -e 's/^\(url: \)\(.*\)$/\2/p' 2>&1)
			echo $URL;
      ;;
    \?)
     	echo "Usage: pastey [OPTION] [FILE]"
			echo "	-h		Shows this help"
			echo "	-f [FILE]	Upload file"
      ;;
		:)
			echo "Option -$OPTARG requires a path to a file"
			;;
  esac
done
